var yes = true;
console.log("The value for yes is " + yes);
var pi = 3.14;
console.log("the value of pi is " + pi);
var sentence = "hello world";
console.log("the sentence says " + sentence);
var oneToFive = [1, 2, 3, 4, 5];
console.log("Number one to five = " + oneToFive);
var y;
y = [31, "yes", -3.6];
